[book]
authors = ["JorelAli"]
multilingual = false
src = "src"
title = "CommandAPI Documentation v8.4.1"

[build]
build-dir = "./../docs/8.4.1"

[output.html]
git-repository-url = "https://github.com/JorelAli/CommandAPI"
default-theme = "rust"
additional-css = ["style.css"]
additional-js = [
    "sidebar.js",
    "mccmd.js",
    "kotlin-dsl.js",
    "jszip.min.js",
    "yaml.min.js",
    "pluginyml.js"
]
mathjax-support = true

[output.html.fold]
enable = true
level = 2