[book]
authors = ["JorelAli"]
multilingual = false
src = "src"
title = "CommandAPI Documentation v4.0"

[build]
build-dir = "./../docs/4.0"

[output.html]
git-repository-url = "https://github.com/JorelAli/CommandAPI"
default-theme = "rust"
additional-css = ["style.css"]
additional-js = ["sidebar.js"]
mathjax-support = true

[output.html.fold]
enable = true